### PR TITLE
BEM-ish classes as default (and viewport div)

### PR DESCRIPTION
**Pull request by feejin**
Your thoughts on default nav markup? I have to add classes every time so thought some standard ones might be handy.

@kinglozzer @stnvh

### CODE REVIEW

**Comment by stnvh** [comment]
Class markup looks good to me, though is it worth putting in aria roles & tabindex ?

**Comment by feejin** [comment]
Aria roles should be in there. Tabindex can mess with forms, I think that's
an "only if we have to" sort of enhancement.

**Comment by kinglozzer** [comment]
Looks okay. I’m not sure that `nav__submenu`/`nav__subitem`/`nav__sublink` are technically correct for BEM but who cares? It’s BEM-ish™, so that’s good enough for me

**Comment by feejin** [comment]
I hate it when it says block__element-something--modifier. The multiple
hyphens are hard to read. The goal of BEMish is to be readable. I think.

**Pull request merged**
